### ISSUE TITLE
Jquery 3 doesnt work...

### ISSUE THREAD

**Issue by xspaniki** [gemgento/rails_script#23]
Hello,

if I use `#= require jquery` or `#= require jquery2` all its fine but for `#= require jquery3` rails_script doesnt work. `$(document).on "ready.rails_script"`isnt triggered.

**Comment by kpheasey** [comment]
Do you see any errors in the browser console?  What happens when you call `RailsScript.init()`?

Take a look at the various namespaces in the initializer.  What Are all your controllers listed under `window.App`?

https://github.com/gemgento/rails_script/blob/master/vendor/assets/javascripts/rails_script/init.coffee#L1-L4

**Comment by xspaniki** [comment]
Browser console is empty. If I call RailsScript.init() in browser console everything works fine. Yes all controller are under `window.App`.

**Comment by kpheasey** [comment]
I'm not familiar with jquery 3, but after a quick search seems to bind document ready in the same manner.  As long as `$` and `jQuery` are available in the window, it shouldn't be an issue.

Are you using turbolinks?

**Comment by xspaniki** [comment]
I pass RailsScript.init() to application.coffee after include rails_script files and looks it works fine :)
thx
