### ISSUE TITLE
Common code across new and edit functions

### ISSUE THREAD

**Issue by krsyoung** [gemgento/rails_script#5]
Hey, this isn't exactly an issue but I'm finding I have a common pattern where I want to reuse the same code across new and edit.  Just curious if there are ideas on the cleanest way to do this.  Was considering between:

1. Define the functions in ```global.js.coffee``` and then just call them in new / edit.  Not sure I'm liking this option.
2. Take an approach like in ```base.js.coffee``` and point the edit function to new (like update points to edit)

Thanks for the ideas (and @gemgento thanks for the awesome code!)

**Comment by kpheasey** [comment]
If it's always the same code in new and edit globally, then calling ```@edit()``` inside of ```new()``` in ```base.js``` would be fine.  However, if there is sometimes a difference, then you would want to do this on a per controller basis.

I imagine a lot of the JS for new and edit actions is related to a form.  In which case, you could create an ```Element``` for the form and initialize it inside both actions.

If this is a satisfactory answer, please close the issue.  Otherwise, just provide some more detail into exactly what your doing and we might be able to come up with a better solution.

**Comment by krsyoung** [comment]
Perfect, I'm going to try the Element approach (it is all form logic -- tokenizer etc..).  If I end up doing something different I'll update this issue for future references.  Thanks @kpheasey
